defmodule Balanced.Card do
    @type t :: %Balanced.Card{
        created_at: binary,
        href: binary, 
        id: binary, 
        links: map, 
        meta: map, 
        updated_at: binary,
        avs_postal_match: binary,
        avs_result: binary,
        avs_street_match: binary,
        brand_name: binary,
        category: binary,
        address: Balanced.Address.t,
        can_credit: boolean,
        can_debit: boolean,
        cvv: binary,
        cvv_result: binary,
        cvv_match: binary,
        expiration_month: number,
        expiration_year: number,
        is_verified: boolean,
        fingerprint: binary,
        number: binary,
        name: binary,
        type: binary
    }

    defstruct [
        :created_at,
        :href ,
        :id ,
        :links ,
        :meta,
        :updated_at,
        :avs_postal_match,
        :avs_result,
        :avs_street_match,
        :brand_name,
        :category,
        :address,
        :can_credit,
        :can_debit,
        :cvv,
        :cvv_result,
        :cvv_match,
        :expiration_month,
        :expiration_year,
        :is_verified,
        :fingerprint,
        :number,
        :name,
        :type
    ]
end